name: MeinPlugin
version: 1.0
main: dev.felix.MainPlugin
api-version: 1.12
commands:
  hallo:
    description: TestHallo
    alias: [hey,hi,heyo]
  aura:
    description: Adds an Effect around you
    alias: [Effect]
    